version: "3"

services: 
  app:
    labels: 
      - "traefik.enabled=true"

  reverse-proxy:
    image: trefik
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock